name: media-players

services:
  plex:
    image: lscr.io/linuxserver/plex:1.43.0
    container_name: plex
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config/plex-config:/config
      - ${DATA_FOLDER}/media:/media
      - ${ADDITIONAL_SHARE}:/media-synology
    environment:
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM} # optional
      - TZ=Europe/Berlin
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
