name: backup-syncthing

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:2.0.13
    container_name: syncthing
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config:/config
      - ${SYNC_DATA_DIR:?error}:/backups
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    ports:
      - "8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: unless-stopped
