services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:2.0.11
    container_name: syncthing
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Zurich
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config:/config
      - ${SYNC_DATA_DIR:?error}:/backups
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
