name: lurk

services:
  lurk:
    image: ghcr.io/jackra1n/lurk:1.0.2
    container_name: lurk
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    restart: unless-stopped
