name: backrest

services:
  backrest:
    image: garethgeorge/backrest:v1.9.2
    container_name: backrest
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/data:/data
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config:/config
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/cache:/cache
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/tmp:/tmp
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/rclone:/root/.config/rclone
      - ${BACKUP_DATA_DIR:?error}:/userdata
      - ${BACKUP_DATA_DEST:?error}:/backups
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Berlin
    ports:
      - "9898:9898"
    restart: unless-stopped
    hostname: backrest
