name: dozzle

services:
  dozzle:
    image: amir20/dozzle:v8.14.12
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/data:/data
    environment:
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      - DOZZLE_ENABLE_ACTIONS=true
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      - DOZZLE_ENABLE_SHELL=true
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      - DOZZLE_AUTH_PROVIDER=simple
    ports:
      - "8808:8080"
