#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.5.0
    container_name: immich_server
    depends_on:
      - database
      - redis
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/library:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    env_file:
      - .env
    ports:
      - "2283:2283"
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          memory: 3G
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.0
    container_name: immich_machine_learning
    volumes:
      - model-cache:/cache
    environment:
      - TZ=Europe/Berlin
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          memory: 4G

  redis:
    image: docker.io/valkey/valkey:8-bookworm@sha256:a19bebed6a91bd5e6e2106fef015f9602a3392deeb7c9ed47548378dcee3dfc2
    container_name: immich_redis
    environment:
      - TZ=Europe/Berlin
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    container_name: immich_postgres
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - TZ=Europe/Berlin
      - POSTGRES_INITDB_ARGS=--data-checksums
    env_file:
      - .env
    restart: always

volumes:
  model-cache:
