name: minecraft_server_vanilla

services:
  minecraft_server_vanilla:
    image: itzg/minecraft-server:java21
    container_name: mc_vanilla
    volumes:
      - ${DOCKER_DATA_DIR:?error}/minecraft/${COMPOSE_PROJECT_NAME:?error}/data:/data
    environment:
      - TZ=Europe/Berlin
    env_file: .env
    ports:
      - "${MINECRAFT_PORT:-25565}:25565"
    restart: unless-stopped
    stdin_open: true
    tty: true
