services:
  czkawka:
    container_name: czkawka
    image: ghcr.io/jlesage/czkawka:v25.08.1
    ports:
      - '5800:5800'
    volumes:
      - ${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/config:/config
      - ${FILES_DIR}:/storage
    environment:
      - USER_ID=1000
      - GROUP_ID=100
      - DARK_MODE=1
    cpus: 8.0
